services:
  mysql_db:
    image: mysql:8.4
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: testpass
      MYSQL_DATABASE: assignmentdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]      
      interval: 5s
      timeout: 5s
      retries: 10

  go_app:
    build: .
    container_name: go_app
    ports:
      - "3000:3000"
    depends_on:
      mysql_db:
        condition: service_healthy
    env_file:
    - .env

volumes:
  db_data:
